name: Deploy WTWR to Google Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Google Cloud
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/chris2fair88
          rm -rf temp-deploy
          git clone https://github.com/Chris2Fair88/se_project_react.git temp-deploy
          cd temp-deploy
          npm ci
          npm run build
          rm -rf /home/chris2fair88/frontend/*
          cp -r dist/* /home/chris2fair88/frontend/
          cd /home/chris2fair88
          rm -rf temp-deploy